### ISSUE TITLE
Power Auras Classic

### ISSUE THREAD

**Issue by Ruralor** [Ascension-Addons/Addon-Requests#1]
### 3.3.5 Compatible version of the addon

https://www.curseforge.com/wow/addons/powerauras-classic/files

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

Buff/Debuff icons and Spell timers with high customization with lower resource usage compared to Weak auras.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/PowerAuras

It is already found here I believe, open an issue there if there is problems with it!
