### ISSUE TITLE
Auto Quest

### ISSUE THREAD

**Issue by BanditTech** [Ascension-Addons/Addon-Requests#10]
### 3.3.5 Compatible version of the addon

https://github.com/BanditTech/AutoQuest-Ascension

### Requires Fixes

- [ ] Yes
- [x] No

### Addon Description

An addon which accepts/completes quests for you. This can be configured to Accept all quests, or just some. Individual quests can be enabled/disabled. 

It has been customized for Ascension to include some of the high risk quests, but I am still adding some more.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/AutoQuest/
