### ISSUE TITLE
Shadowed Unit Frames

### ISSUE THREAD

**Issue by Luciqqheh** [Ascension-Addons/Addon-Requests#11]
### 3.3.5 Compatible version of the addon

https://www.curseforge.com/wow/addons/shadowed-unit-frames/files/435570

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

It is UI addon, for frames etc. 
https://www.curseforge.com/wow/addons/shadowed-unit-frames

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/ShadowedUnitFrames was disabled on launcher(?), reenabled
