### ISSUE TITLE
TellMeWhen

### ISSUE THREAD

**Issue by Luciqqheh** [Ascension-Addons/Addon-Requests#12]
### 3.3.5 Compatible version of the addon

https://www.curseforge.com/wow/addons/tellmewhen/files/448968

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

Addon similar to Weakauras and Powerauras.
"TellMeWhen is a WoW addon that provides visual, auditory, and textual notifications about cooldowns, buffs, and pretty much every other element of combat."

_(Not sure with the fixis, it should not really need any in theory)_

**Comment by andrew6180** [comment]
I think weakauras covers the entire use case of this addon. While some may prefer tellmewhen over weakauras, maintaining both would be a huge task when there is likely very few people who will use this over weakauras.
