### ISSUE TITLE
Mik Scrolling Battle Text

### ISSUE THREAD

**Issue by Bromeego** [Ascension-Addons/Addon-Requests#13]
### 3.3.5 Compatible version of the addon

https://www.curseforge.com/wow/addons/mik-scrolling-battle-text/download/422879 or if this doesn't work it can be found here https://www.curseforge.com/wow/addons/mik-scrolling-battle-text/files/all?page=3

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

An excellent add-on for combat numbers. Consolidating aoe numbers into one and is one of the core addons when tweaking your UI.

I have been using this since joining Ascension and have had no issues using it. Would be awesome to have on the launcher.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/MikScrollingBattleText

This is now on the launcher. 

Thank you for your contribution!
