### ISSUE TITLE
AscendedSkillCards

### ISSUE THREAD

**Issue by Sigbear** [Ascension-Addons/Addon-Requests#14]
### 3.3.5 Compatible version of the addon

https://github.com/Sigbear/AscendedSkillCards

currently https://github.com/Sigbear/AscendedSkillCards/releases/download/1.4.2/AscendedSkillCards.7z is the lastest

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

A small quality of life addon that helps with the process of keeping track of, and handling your skill cards. 
The addon provides a compact interface with the current featuers:
 - current count of skill cards in your inventory
 - one click buttons for exchanging skill cards (no need to switch between tabs at the npc)
 - a list of unknown skill cards in your inventory, which can be clicked and learned directly from the ui.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/AscendedSkillCards

Sorry for the late response on this!

Thank you for your contribution! If you would like to update the addon, please create a pull request to this repo from now on!
