### ISSUE TITLE
MobSpells

### ISSUE THREAD

**Issue by mattcapazz** [Ascension-Addons/Addon-Requests#16]
### 3.3.5 Compatible version of the addon

[MobSpells.zip](https://github.com/Ascension-Addons/Addon-Requests/files/11507717/MobSpells.zip)

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

This addon adds creature spells to the GameTooltip.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/MobSpells

Thank you for your contribution!
