### ISSUE TITLE
SuperDuperMacro

### ISSUE THREAD

**Issue by mattcapazz** [Ascension-Addons/Addon-Requests#17]
### 3.3.5 Compatible version of the addon

[SuperDuperMacro.zip](https://github.com/Ascension-Addons/Addon-Requests/files/11637717/SuperDuperMacro.zip)

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

allows the player to create long macros.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/SuperDuperMacro 

Thank you for the contribution
