### ISSUE TITLE
Clear Quests

### ISSUE THREAD

**Issue by BanditTech** [Ascension-Addons/Addon-Requests#19]
### 3.3.5 Compatible version of the addon

https://github.com/BanditTech/ClearQuests

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

Provides a simple interface for clearing out your quest log. This is very useful during prestige runs. 

![Ascension_3qShBT6Frd](https://github.com/Ascension-Addons/Addon-Requests/assets/13251996/da6338b9-6a31-4590-9101-114372df3f95)

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/ClearQuests
