### ISSUE TITLE
RatingBuster

### ISSUE THREAD

**Issue by Luciqqheh** [Ascension-Addons/Addon-Requests#2]
### 3.3.5 Compatible version of the addon

https://www.curseforge.com/wow/addons/rating-buster

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

- Rating Conversion:
- Converts combat ratings into percentages.
- Stat Breakdown:
- Breakdown Strength, Agility, Stamina, Intellect and Spirit into base stats.
- Supports talents, buffs and racials that give you extra bonuses.
- Ex: Lunar Guidance - "Increases your spell damage and healing by 8/16/25% of your total Intellect."
- Ex: Heart of the Wild - "Increases your Intellect by 4/8/12/16/20%. In addition, ......etc"
- Ex: +13 Intellect (+234 Mana, +0.18% Spell Crit, +3.9 Dmg)

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/RatingBuster

Will be updated before Season 8 starts on the 28th!
