### ISSUE TITLE
Tellmewhen

### ISSUE THREAD

**Issue by NinjaPumpkin** [Ascension-Addons/Addon-Requests#20]
### 3.3.5 Compatible version of the addon

https://www.curseforge.com/wow/addons/tellmewhen

There are different versions but it seems like this addon was not made for 3.3.5 however, someone made a slightly dumbed down version which can be found here.

https://github.com/bkader/TellMeWhen_3.3.5

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

This addon displays all combat information seamlessly, I can even put in conditions for when I want X to appear, for example, i want it to show me heroic strike only when rage is above 40% and target's life is under 20% (conditions can be alot more complex than this) but you understand how this can be a very powerful too. I like it instead of WA because it just works the way I like it too. It is alot more customizable and extensive when compared to other mods. 

https://www.curseforge.com/wow/addons/tellmewhen

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/Addon-Requests/issues/12#issuecomment-2558620114
