### ISSUE TITLE
SellOMatic

### ISSUE THREAD

**Issue by lazyloafs** [Ascension-Addons/Addon-Requests#23]
### 3.3.5 Compatible version of the addon

https://github.com/lazyloafs/sellomatic

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

Adds buttons to vendor menu, Iterates through bags and sells items of a certain quality instantly to vendor.

**Comment by andrew6180** [comment]
Theres a handful of issues with this that I'm going to pass on adding it to the launcher. 

- Items are hardcoded names, we have multiple supported languages now and this would not work on any of them
- ADDON_LOADED is implemented wrong so this creates a bunch of buttons every time any addon loads
- There is already a pretty extensive / configurable auto sell addon on the launcher. 
- Pollutes the global namespace with pretty generic names such as `"CreateSellButtons"`

Sorry for the very late response!
