### ISSUE TITLE
Loot Rememberer

### ISSUE THREAD

**Issue by bilalakil** [Ascension-Addons/Addon-Requests#24]
### 3.3.5 Compatible version of the addon

https://github.com/bilalakil/loot-rememberer

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

Right click on need, greed, disenchant or pass to remember the selection for that item and auto-apply it in future. Supports stock UI and ElvUI (tested on v7.16). Type /lootrememberer to browse and delete saved records.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/loot-rememberer
