### ISSUE TITLE
RPstatus

### ISSUE THREAD

**Issue by codexkeeper** [Ascension-Addons/Addon-Requests#27]
### 3.3.5 Compatible version of the addon

https://github.com/codexkeeper/RPStatus

### Requires Fixes

- [ ] Yes
- [X] No

### Addon Description

i created this lightweight addon specifically for a Ascension Guild RP but i guess there are some others interested too. 

It shows the players in guild / party / raid  who have this addon isntalled and let's you toggle your search for rp status and see if others are looking for rp.  That way we could start an RP HC-Run together.

**Comment by code-llew** [comment]
+1 to this! This could really help to open up a whole new side of the Ascension community. Get this on the Launcher!

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/RPStatus
