### ISSUE TITLE
Requesting an addon called AfterCast

### ISSUE THREAD

**Issue by g0sy** [Ascension-Addons/Addon-Requests#28]
### 3.3.5 Compatible version of the addon

https://www.wowinterface.com/downloads/info14404-AfterCastFansUpdate.html#info

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

This is a fairly simple addon for performing actions based on the success or failure of a cast.
/aftercast /smile
/aftercast +fail /cry
/cast Frostbolt(Rank 2)

**Comment by andrew6180** [comment]
Believe most if not all of this could be accomplished through weakauras pretty easily. I think this addon likely requires too much text to explain how to use it to be useful on the launcher.
