### ISSUE TITLE
Trainer

### ISSUE THREAD

**Issue by Kaolyr** [Ascension-Addons/Addon-Requests#29]
### 3.3.5 Compatible version of the addon

https://www.curseforge.com/wow/addons/trainer (2.4.3 compatible)

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

This unvaluable addon displays every class and profession trainers in all cities.
I've tested it, and even after editing the line: "if ( buildVersionMajor > "2" ) then	printPC( pc_colour_Highlight.. L["Requires The Burning Crusade (2.4.3) or lower"] )", replacing the "2" with "3", "4" or "5", it doesn't show the trainers on the map.

**Comment by andrew6180** [comment]
This is something that can be added baseline to Ascension and would likely be very useful. Will see what we can do.
