### ISSUE TITLE
UnitFramesImproved

### ISSUE THREAD

**Issue by Luciqqheh** [Ascension-Addons/Addon-Requests#3]
### 3.3.5 Compatible version of the addon

https://www.curseforge.com/wow/addons/unitframesimproved/files/503920

Ik now it is Cata version, but it used to work normally before the latest update on Ascension. Addition of Primary Stat icon however broke it. 

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

This addon aims to improve upon the standard blizzard unitframes without going beyond the boundaries set by them. Due to this, the addons memory usage is very small as all the hard work to get the unitframes to work is already done by Blizzard.

It just makes default frames better.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/UnitFramesImproved
