### ISSUE TITLE
Add MouselookHandler (Mouse Look) to ascension addons

### ISSUE THREAD

**Issue by eyenf1** [Ascension-Addons/Addon-Requests#30]
### 3.3.5 Compatible version of the addon

Only 3.4.3 version available.
https://www.curseforge.com/wow/addons/mouselookhandler/files/5638190

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

MouselookHandler can lock you into mouselook, so you don't have to constantly press the right mouse button. It also allows rebinding your left and right mouse buttons to something new while mouselook is enabled. By default, it rebinds them to strafe left and right.

**Comment by eyenf1** [comment]
I am currently using a macro that allows me to toggle mouse look but I can't rebind my left and right mouse buttons like this addon allows.

Macro Commands: /run if IsMouselooking() then MouselookStop() else MouselookStart() end

Thanks for your time looking at this request, I'll wait and hope you consider making an updated version that works with ascension.

**Comment by andrew6180** [comment]
This relies heavily on functionality that just doesn't exist in the version of the game Ascension uses (3.3.5). Sadly I think implementing support for it would be fairly difficult for an incredibly niche feature. Hopefully your macro gets you most of the way there, sorry!
