### ISSUE TITLE
EventAlert

### ISSUE THREAD

**Issue by krahoz** [Ascension-Addons/Addon-Requests#5]
### 3.3.5 Compatible version of the addon

Github: https://github.com/krahoz/EventAlert
on Szyler's discord: #eventalert

Changes compared to the original addon from wowinterface:
- Removed all class dependencies
- Removed Sacred shield related code
- Added option to reset the default EventItems in the WTF folder with a click of a button
- Added option to reset the default Alt EventItems in the WTF folder with a click of a button
- Added option to Delete all Custom EventItems in the WTF folder with a click of a button
- Added NOTE that not all Ascension related spells might appear in the Combat log. If you find one, create a bugreport.
- Fixed spell stack counter
- Fixed CustomEvent spell selector not clearing after deleting an item
- Fixed the Class/Alternate checklist display
- Removed/Refactored some old code

Since I removed all class dependecies, it should work with CoA (not confirmed, i don't have CoA)

### Requires Fixes

- [ ] Yes
- [X] No

### EventAlert
Compact addon for displaying procs in the middle of the screen. The addon will notify you in the middle of your screen with an icon, name of the spell that has procced, the time left on the proc and will make a subtle sound. EventAlert is also able to handle more than one proc at a time. The mod should work on install without any config, but if you wish to change any options use the following command: /ea options

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/EventAlert
