### ISSUE TITLE
Omen

### ISSUE THREAD

**Issue by krahoz** [Ascension-Addons/Addon-Requests#6]
### 3.3.5 Compatible version of the addon

https://github.com/krahoz/Omen
on Szyler's discord #omen

Changes compared to the original addon on wowinterface:
- Added and Updated Omen for 2022-10-18 core merge compatibility
- Added HERO class
- Added Tank Stance handling for Ascension (including Mana-forged Barrier) - warning logic

What requires fixing?
- Probably doesn't work with CoA, since i only adde the Hero class
- 100% works with Area52!!

### Requires Fixes

- [X] Yes
- [ ] No

### Omen is a threat meter
Omen provides accurate values of your group's relative threat level on individual enemies and you can see when you're in danger of pulling aggro. This info is usually only critical in raids, where only tanks can survive aggro, but it's useful for any multi-player situation.

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/Omen/
