### ISSUE TITLE
PlateBuffs

### ISSUE THREAD

**Issue by krahoz** [Ascension-Addons/Addon-Requests#7]
### 3.3.5 Compatible version of the addon

https://github.com/krahoz/PlateBuffs
on Szyler's discord: #platebuffs

I don't remember where i got the original addon, it was years ago, i copied it over from my old wow client backup. Probably CurseForge or WowInterface.

Doesn't require fixing, it creates a frames above the nameplates with icons and attaches other frames to it, no class dependency

### Requires Fixes

- [ ] Yes
- [X] No

### PlateBuffs
PlateBuffs displays people's buffs or debuffs above their nameplates.

![unknown](https://user-images.githubusercontent.com/109991939/199327480-29e8ea5b-5a7a-4a2d-be63-32a999751199.png)

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/PlateBuffs
