### ISSUE TITLE
TradeSkillMaster

### ISSUE THREAD

**Issue by BanditTech** [Ascension-Addons/Addon-Requests#8]
### 3.3.5 Compatible version of the addon

https://github.com/andrew6180/TradeSkillMaster

### Requires Fixes

- [X] Yes
- [ ] No

### Addon Description

A wonderful crafting workflow addon which allows for the automation of several aspects of crafting and selling items.

It requires a few adjustments to work with our enchanting vellum, as well as introduction of crafting recipe that are only available on the Ascension server. Most of these adjustments are already available https://github.com/BanditTech/TradeSkillMaster-Ascension

Recently it is having issues though, and not sure why. Would be another wonderful addition to the launcher addons.

**Comment by andrew6180** [comment]
Addon is too buggy to put up on launcher atm but it's something I'd like to get around to at some point. Will put it in our repo so its centralized but won't be on launcher until I feel it's working enough in most use cases.

https://github.com/Ascension-Addons/TradeSkillMaster
