### ISSUE TITLE
Broker_Portals

### ISSUE THREAD

**Issue by mattcapazz** [Ascension-Addons/Addon-Requests#9]
### 3.3.5 Compatible version of the addon

https://github.com/mattcapazz/asc_Broker_Portals

### Requires Fixes

- [ ] Yes
- [X] No

### Broker_Portals
Broker_Portals provides access to all Portal and Teleport spells on right click of one button.

![example.png](https://github.com/mattcapazz/asc_Broker_Portals/raw/main/example.png)

**Comment by andrew6180** [comment]
https://github.com/Ascension-Addons/Broker-Portals
